
env:
  global:
    - PACKAGE_VERSION="0.1.0"
matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.0
      before_install: cd src
      solution: VCEL.sln
      install: dotnet restore VCEL.sln
      script: 
        - dotnet build VCEL.sln /p:Configuration=Release /p:Version=${PACKAGE_VERSION}-pre-$TRAVIS_BUILD_NUMBER /p:AssemblyVersion=${PACKAGE_VERSION}.$TRAVIS_BUILD_NUMBER
      after_script:
        - dotnet test
      # after_success:
      # - test $TRAVIS_BRANCH = "master" && dotnet nuget push bin/Release/VCEL.${PACKAGE_VERSION}-pre-${TRAVIS_BUILD_NUMBER}.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json