using NUnit.Framework;
using System.Collections.Generic;
using VCEL.Core.Expression.Impl;

namespace VCEL.Test
{
    public class TypeOperationTests
    {
        [TestCaseSource(nameof(Cases))]
        public void ShouldTest(object left, object right, bool expected)
        {
            Assert.AreEqual(expected, TypeOperation.EqualsChecked(left, right), "Left Right");
            Assert.AreEqual(expected, TypeOperation.EqualsChecked(right, left), "Right Left");
        }

        public static object?[] Cases =
        {
            new object?[] { null, null, true },
            new object?[] { null, 0, false },
            new object?[] { null, "", false },

            new object?[] { 0, 0, true },

            new object?[] { 1, 1, true },
            new object?[] { 1, 1U, true },
            new object?[] { 1, (short)1, true },
            new object?[] { 1, (ushort)1, true },
            new object?[] { 1, 1L, true },
            new object?[] { 1, 1UL, true },
            new object?[] { 1, 1d, true },
            new object?[] { 1, 1f, true },
            new object?[] { 1, 1m, true },
            new object?[] { 1, 2, false },
            new object?[] { 1, 2U, false },
            new object?[] { 1, (short)2, false },
            new object?[] { 1, (ushort)2, false },
            new object?[] { 1, 2L, false },
            new object?[] { 1, 2UL, false },
            new object?[] { 1, 2d, false },
            new object?[] { 1, 2f, false },
            new object?[] { 1, 2m, false },
            new object?[] { int.MaxValue, int.MaxValue, true },
            new object?[] { int.MaxValue, uint.MaxValue, false },
            new object?[] { int.MaxValue, short.MaxValue, false },
            new object?[] { int.MaxValue, ushort.MaxValue, false },
            new object?[] { int.MaxValue, long.MaxValue, false },
            new object?[] { int.MaxValue, ulong.MaxValue, false },
            new object?[] { int.MaxValue, double.MaxValue, false },
            new object?[] { int.MaxValue, float.MaxValue, false },
            new object?[] { int.MaxValue, decimal.MaxValue, false },

            new object?[] { (short)1, 1, true },
            new object?[] { (short)1, 1U, true },
            new object?[] { (short)1, (short)1, true },
            new object?[] { (short)1, (ushort)1, true },
            new object?[] { (short)1, 1L, true },
            new object?[] { (short)1, 1UL, true },
            new object?[] { (short)1, 1d, true },
            new object?[] { (short)1, 1f, true },
            new object?[] { (short)1, 1m, true },
            new object?[] { (short)1, 2, false },
            new object?[] { (short)1, 2U, false },
            new object?[] { (short)1, (short)2, false },
            new object?[] { (short)1, (ushort)2, false },
            new object?[] { (short)1, 2L, false },
            new object?[] { (short)1, 2UL, false },
            new object?[] { (short)1, 2d, false },
            new object?[] { (short)1, 2f, false },
            new object?[] { (short)1, 2m, false },
            new object?[] { short.MaxValue, int.MaxValue, false },
            new object?[] { short.MaxValue, uint.MaxValue, false },
            new object?[] { short.MaxValue, short.MaxValue, true },
            new object?[] { short.MaxValue, ushort.MaxValue, false },
            new object?[] { short.MaxValue, long.MaxValue, false },
            new object?[] { short.MaxValue, ulong.MaxValue, false },
            new object?[] { short.MaxValue, double.MaxValue, false },
            new object?[] { short.MaxValue, float.MaxValue, false },
            new object?[] { short.MaxValue, decimal.MaxValue, false },

            new object?[] { 1L, 1, true },
            new object?[] { 1L, 1U, true },
            new object?[] { 1L, (short)1, true },
            new object?[] { 1L, (ushort)1, true },
            new object?[] { 1L, 1L, true },
            new object?[] { 1L, 1UL, true },
            new object?[] { 1L, 1d, true },
            new object?[] { 1L, 1f, true },
            new object?[] { 1L, 1m, true },
            new object?[] { 1L, 2, false },
            new object?[] { 1L, 2U, false },
            new object?[] { 1L, (short)2, false },
            new object?[] { 1L, (ushort)2, false },
            new object?[] { 1L, 2L, false },
            new object?[] { 1L, 2UL, false },
            new object?[] { 1L, 2d, false },
            new object?[] { 1L, 2f, false },
            new object?[] { 1L, 2m, false },
            new object?[] { long.MaxValue, int.MaxValue, false },
            new object?[] { long.MaxValue, uint.MaxValue, false },
            new object?[] { long.MaxValue, short.MaxValue, false },
            new object?[] { long.MaxValue, ushort.MaxValue, false },
            new object?[] { long.MaxValue, long.MaxValue, true },
            new object?[] { long.MaxValue, ulong.MaxValue, false },
            new object?[] { long.MaxValue, double.MaxValue, false },
            new object?[] { long.MaxValue, float.MaxValue, false },
            new object?[] { long.MaxValue, decimal.MaxValue, false },

            new object?[] { 1d, 1, true },
            new object?[] { 1d, 1U, true },
            new object?[] { 1d, (short)1, true },
            new object?[] { 1d, (ushort)1, true },
            new object?[] { 1d, 1L, true },
            new object?[] { 1d, 1UL, true },
            new object?[] { 1d, 1d, true },
            new object?[] { 1d, 1f, true },
            new object?[] { 1d, 1m, true },
            new object?[] { 1d, 2, false },
            new object?[] { 1d, 2U, false },
            new object?[] { 1d, (short)2, false },
            new object?[] { 1d, (ushort)2, false },
            new object?[] { 1d, 2L, false },
            new object?[] { 1d, 2UL, false },
            new object?[] { 1d, 2d, false },
            new object?[] { 1d, 2f, false },
            new object?[] { 1d, 2m, false },
            new object?[] { double.MaxValue, int.MaxValue, false },
            new object?[] { double.MaxValue, uint.MaxValue, false },
            new object?[] { double.MaxValue, short.MaxValue, false },
            new object?[] { double.MaxValue, ushort.MaxValue, false },
            new object?[] { double.MaxValue, long.MaxValue, false },
            new object?[] { double.MaxValue, ulong.MaxValue, false },
            new object?[] { double.MaxValue, double.MaxValue, true },
            new object?[] { double.MaxValue, float.MaxValue, false },
            new object?[] { double.MaxValue, decimal.MaxValue, false },

            new object?[] { 1f, 1, true },
            new object?[] { 1f, 1U, true },
            new object?[] { 1f, (short)1, true },
            new object?[] { 1f, (ushort)1, true },
            new object?[] { 1f, 1L, true },
            new object?[] { 1f, 1UL, true },
            new object?[] { 1f, 1d, true },
            new object?[] { 1f, 1f, true },
            new object?[] { 1f, 1m, true },
            new object?[] { 1f, 2, false },
            new object?[] { 1f, 2U, false },
            new object?[] { 1f, (short)2, false },
            new object?[] { 1f, (ushort)2, false },
            new object?[] { 1f, 2L, false },
            new object?[] { 1f, 2UL, false },
            new object?[] { 1f, 2d, false },
            new object?[] { 1f, 2f, false },
            new object?[] { 1f, 2m, false },
            new object?[] { float.MaxValue, int.MaxValue, false },
            new object?[] { float.MaxValue, uint.MaxValue, false },
            new object?[] { float.MaxValue, short.MaxValue, false },
            new object?[] { float.MaxValue, ushort.MaxValue, false },
            new object?[] { float.MaxValue, long.MaxValue, false },
            new object?[] { float.MaxValue, ulong.MaxValue, false },
            new object?[] { float.MaxValue, double.MaxValue, false },
            new object?[] { float.MaxValue, float.MaxValue, true },
            new object?[] { float.MaxValue, decimal.MaxValue, false },

            new object?[] { 1m, 1, true },
            new object?[] { 1m, 1U, true },
            new object?[] { 1m, (short)1, true },
            new object?[] { 1m, (ushort)1, true },
            new object?[] { 1m, 1L, true },
            new object?[] { 1m, 1UL, true },
            new object?[] { 1m, 1d, true },
            new object?[] { 1m, 1f, true },
            new object?[] { 1m, 1m, true },
            new object?[] { 1m, 2, false },
            new object?[] { 1m, 2U, false },
            new object?[] { 1m, (short)2, false },
            new object?[] { 1m, (ushort)2, false },
            new object?[] { 1m, 2L, false },
            new object?[] { 1m, 2UL, false },
            new object?[] { 1m, 2d, false },
            new object?[] { 1m, 2f, false },
            new object?[] { 1m, 2m, false },
            new object?[] { decimal.MaxValue, int.MaxValue, false },
            new object?[] { decimal.MaxValue, uint.MaxValue, false },
            new object?[] { decimal.MaxValue, short.MaxValue, false },
            new object?[] { decimal.MaxValue, ushort.MaxValue, false },
            new object?[] { decimal.MaxValue, long.MaxValue, false },
            new object?[] { decimal.MaxValue, ulong.MaxValue, false },
            new object?[] { decimal.MaxValue, double.MaxValue, false },
            new object?[] { decimal.MaxValue, float.MaxValue, false },
            new object?[] { decimal.MaxValue, decimal.MaxValue, true },
            new object?[] { decimal.MaxValue, (double)decimal.MaxValue, false },
            new object?[] { decimal.MaxValue, (float)decimal.MaxValue, false },

            new object?[] { -1, -1, true },
            new object?[] { -1, -1U, true },
            new object?[] { -1, (short)-1, true },
            new object?[] { -1, -1L, true },
            new object?[] { -1, -1d, true },
            new object?[] { -1, -1f, true },
            new object?[] { -1, -1m, true },
            new object?[] { -1, -2, false },
            new object?[] { -1, -2U, false },
            new object?[] { -1, (short)-2, false },
            new object?[] { -1, -2L, false },
            new object?[] { -1, -2d, false },
            new object?[] { -1, -2f, false },
            new object?[] { -1, -2m, false },
            new object?[] { int.MinValue, int.MinValue, true },
            new object?[] { int.MinValue, uint.MinValue, false },
            new object?[] { int.MinValue, short.MinValue, false },
            new object?[] { int.MinValue, ushort.MinValue, false },
            new object?[] { int.MinValue, long.MinValue, false },
            new object?[] { int.MinValue, ulong.MinValue, false },
            new object?[] { int.MinValue, double.MinValue, false },
            new object?[] { int.MinValue, float.MinValue, false },
            new object?[] { int.MinValue, decimal.MinValue, false },

            new object?[] { -(short)1, -1, true },
            new object?[] { -(short)1, -1U, true },
            new object?[] { -(short)1, (short)-1, true },
            new object?[] { -(short)1, -1L, true },
            new object?[] { -(short)1, -1d, true },
            new object?[] { -(short)1, -1f, true },
            new object?[] { -(short)1, -1m, true },
            new object?[] { -(short)1, -2, false },
            new object?[] { -(short)1, -2U, false },
            new object?[] { -(short)1, (short)-2, false },
            new object?[] { -(short)1, -2L, false },
            new object?[] { -(short)1, -2d, false },
            new object?[] { -(short)1, -2f, false },
            new object?[] { -(short)1, -2m, false },
            new object?[] { short.MinValue, int.MinValue, false },
            new object?[] { short.MinValue, uint.MinValue, false },
            new object?[] { short.MinValue, short.MinValue, true },
            new object?[] { short.MinValue, ushort.MinValue, false },
            new object?[] { short.MinValue, long.MinValue, false },
            new object?[] { short.MinValue, ulong.MinValue, false },
            new object?[] { short.MinValue, double.MinValue, false },
            new object?[] { short.MinValue, float.MinValue, false },
            new object?[] { short.MinValue, decimal.MinValue, false },

            new object?[] { -1L, -1, true },
            new object?[] { -1L, -1U, true },
            new object?[] { -1L, (short)-1, true },
            new object?[] { -1L, -1L, true },
            new object?[] { -1L, -1d, true },
            new object?[] { -1L, -1f, true },
            new object?[] { -1L, -1m, true },
            new object?[] { -1L, -2, false },
            new object?[] { -1L, -2U, false },
            new object?[] { -1L, (short)-2, false },
            new object?[] { -1L, -2L, false },
            new object?[] { -1L, -2d, false },
            new object?[] { -1L, -2f, false },
            new object?[] { -1L, -2m, false },
            new object?[] { long.MinValue, int.MinValue, false },
            new object?[] { long.MinValue, uint.MinValue, false },
            new object?[] { long.MinValue, short.MinValue, false },
            new object?[] { long.MinValue, ushort.MinValue, false },
            new object?[] { long.MinValue, long.MinValue, true },
            new object?[] { long.MinValue, ulong.MinValue, false },
            new object?[] { long.MinValue, double.MinValue, false },
            new object?[] { long.MinValue, float.MinValue, false },
            new object?[] { long.MinValue, decimal.MinValue, false },

            new object?[] { -1d, -1, true },
            new object?[] { -1d, -1U, true },
            new object?[] { -1d, (short)-1, true },
            new object?[] { -1d, -1L, true },
            new object?[] { -1d, -1d, true },
            new object?[] { -1d, -1f, true },
            new object?[] { -1d, -1m, true },
            new object?[] { -1d, -2, false },
            new object?[] { -1d, -2U, false },
            new object?[] { -1d, (short)-2, false },
            new object?[] { -1d, -2L, false },
            new object?[] { -1d, -2d, false },
            new object?[] { -1d, -2f, false },
            new object?[] { -1d, -2m, false },
            new object?[] { double.MinValue, int.MinValue, false },
            new object?[] { double.MinValue, uint.MinValue, false },
            new object?[] { double.MinValue, short.MinValue, false },
            new object?[] { double.MinValue, ushort.MinValue, false },
            new object?[] { double.MinValue, long.MinValue, false },
            new object?[] { double.MinValue, ulong.MinValue, false },
            new object?[] { double.MinValue, double.MinValue, true },
            new object?[] { double.MinValue, float.MinValue, false },
            new object?[] { double.MinValue, decimal.MinValue, false },

            new object?[] { -1f, -1, true },
            new object?[] { -1f, -1U, true },
            new object?[] { -1f, (short)-1, true },
            new object?[] { -1f, -1L, true },
            new object?[] { -1f, -1d, true },
            new object?[] { -1f, -1f, true },
            new object?[] { -1f, -1m, true },
            new object?[] { -1f, -2, false },
            new object?[] { -1f, -2U, false },
            new object?[] { -1f, (short)-2, false },
            new object?[] { -1f, -2L, false },
            new object?[] { -1f, -2d, false },
            new object?[] { -1f, -2f, false },
            new object?[] { -1f, -2m, false },
            new object?[] { float.MinValue, int.MinValue, false },
            new object?[] { float.MinValue, uint.MinValue, false },
            new object?[] { float.MinValue, short.MinValue, false },
            new object?[] { float.MinValue, ushort.MinValue, false },
            new object?[] { float.MinValue, long.MinValue, false },
            new object?[] { float.MinValue, ulong.MinValue, false },
            new object?[] { float.MinValue, double.MinValue, false },
            new object?[] { float.MinValue, float.MinValue, true },
            new object?[] { float.MinValue, decimal.MinValue, false },

            new object?[] { -1m, -1, true },
            new object?[] { -1m, -1U, true },
            new object?[] { -1m, (short)-1, true },
            new object?[] { -1m, -1L, true },
            new object?[] { -1m, -1d, true },
            new object?[] { -1m, -1f, true },
            new object?[] { -1m, -1m, true },
            new object?[] { -1m, -2, false },
            new object?[] { -1m, -2U, false },
            new object?[] { -1m, (short)-2, false },
            new object?[] { -1m, -2L, false },
            new object?[] { -1m, -2d, false },
            new object?[] { -1m, -2f, false },
            new object?[] { -1m, -2m, false },
            new object?[] { decimal.MinValue, int.MinValue, false },
            new object?[] { decimal.MinValue, uint.MinValue, false },
            new object?[] { decimal.MinValue, short.MinValue, false },
            new object?[] { decimal.MinValue, ushort.MinValue, false },
            new object?[] { decimal.MinValue, long.MinValue, false },
            new object?[] { decimal.MinValue, ulong.MinValue, false },
            new object?[] { decimal.MinValue, double.MinValue, false },
            new object?[] { decimal.MinValue, float.MinValue, false },
            new object?[] { decimal.MinValue, decimal.MinValue, true },
            new object?[] { decimal.MinValue, (double)decimal.MinValue, false },
            new object?[] { decimal.MinValue, (float)decimal.MinValue, false },

            new object?[] { "", "", true },
            new object?[] { "text", "text", true },
            new object?[] { "text", "string", false },
            new object?[] { 'a', 'a', true },
            new object?[] { '1', 1, false },
            new object?[] { "1", 1, false },

            new object?[] { new int[] { 1 }, new int[] { 1 }, false },
            new object?[] { new List<int> { 1 }, new List<int> { 1 }, false },
        };
    }
}
